server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm;

    charset utf-8;
    client_max_body_size 1M; # Ajustado para sitio estático (no hay subidas)

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/x-javascript
        application/xml
        application/xml+rss
        image/svg+xml
        font/woff2;


    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location ~* \.html$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        log_not_found off;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "OK";
    }
}